table 'cfpb fact_complaints'
	lineageTag: a43a55d0-99b8-4057-b7cd-2d16fbeb8ead

	measure Total_Complaints_Today =
			
			CALCULATE(
			    COUNTROWS('cfpb fact_complaints'),
			    FILTER(
			        'cfpb dim_date',
			        'cfpb dim_date'[full_date] <= TODAY()
			    )
			)
		displayFolder: [complaints]
		lineageTag: ef7cdd6a-c7ae-4830-8b64-841599fed968

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Total_Complaints_30_Days_Ago =
			
			VAR SelectedDate = MAX('cfpb dim_date'[full_date])
			RETURN
			CALCULATE(
			    COUNTROWS('cfpb fact_complaints'),
			    FILTER(
			        'cfpb dim_date',
			        'cfpb dim_date'[full_date] <= SelectedDate - 30
			    )
			)
		formatString: 0
		displayFolder: [complaints]
		lineageTag: d4df4910-f3a0-434b-8446-387964b10eb3

	measure Total_Complaints_60_Days_Ago =
			
			VAR SelectedDate = MAX('cfpb dim_date'[full_date])
			RETURN
			CALCULATE(
			    COUNTROWS('cfpb fact_complaints'),
			    FILTER(
			        'cfpb dim_date',
			        'cfpb dim_date'[full_date] <= SelectedDate - 60
			    )
			)
		formatString: 0
		displayFolder: [complaints]
		lineageTag: 6c54f96e-41c9-446c-8ffe-edf22771ea25

	measure Complaints_Same_Period_Last_Year =
			
			VAR SelectedDate = MAX('cfpb dim_date'[full_date])
			VAR StartDateLY = SelectedDate - 395
			VAR EndDateLY = SelectedDate - 365
			RETURN
			CALCULATE(
			    COUNTROWS('cfpb fact_complaints'),
			    FILTER(
			        'cfpb dim_date',
			        'cfpb dim_date'[full_date] >= StartDateLY &&
			        'cfpb dim_date'[full_date] <= EndDateLY
			    )
			)
		formatString: 0
		displayFolder: [complaints]
		lineageTag: c73ab5f8-c694-4150-bf6a-b088a533cdff

	measure 'Complaints Vs 30 Days' = ```
			
			VAR t = [Total_Complaints_Today] // Complaints today
			VAR p = [Total_Complaints_30_Days_Ago] // Complaints previous 30 days
			VAR r = t - p // Complaint difference betweet today and prev 30 days
			VAR pc = DIVIDE(r, t, 0) // Percentage change
			VAR direction = IF(r >= 0, "↑", "↓")
			
			RETURN
			direction & " " & FORMAT(ABS(r), "#,0") & " vs 30 days (" & FORMAT(ABS(pc), "0.0%") & " change)"
			
			
			```
		displayFolder: [complaints][comparison]
		lineageTag: 3aecdccb-fe12-43f5-ad98-823d045c4ed7

	measure Complaints_Change_Color_Code = IF([Total_Complaints_Today] - [Total_Complaints_30_Days_Ago] >= 0, 1, 0)
		formatString: 0
		displayFolder: [complaints][color_coding]
		lineageTag: d758efd7-fb53-4d43-ac94-0535f93e188e

	measure 'Complaints Vs 60 Days' = ```
			
			VAR t = [Total_Complaints_Today] // Complaints today
			VAR p = [Total_Complaints_60_Days_Ago] // Complaints previous 60 days
			VAR r = t - p // Complaint difference betweet today and prev 60 days
			VAR pc = DIVIDE(r, t, 0) // Percentage change
			VAR direction = IF(r >= 0, "↑", "↓")
			
			RETURN
			direction & " " & FORMAT(ABS(r), "#,0") & " vs 60 days (" & FORMAT(ABS(pc), "0.0%") & " change)"
			
			
			```
		displayFolder: [complaints][comparison]
		lineageTag: d2dc4cf9-e709-4ac4-adaa-58eb0325f0b7

	measure 'Complaints Vs Same Period Last Year' = ```
			
			VAR t = [Total_Complaints_Today] // Complaints today
			VAR p = [Complaints_Same_Period_Last_Year] // Complaints previous year
			VAR r = t - p // Complaint difference betweet today and prev year
			VAR pc = DIVIDE(r, t, 0) // Percentage change
			VAR direction = IF(r >= 0, "↑", "↓")
			
			RETURN
			direction & " " & FORMAT(ABS(r), "#,0") & " vs Same Period Last Year (" & FORMAT(ABS(pc), "0.0%") & " change)"
			
			
			```
		displayFolder: [complaints][comparison]
		lineageTag: dbae2ff2-953e-433d-99e1-16ead1da1f09

	measure Complaints = DISTINCTCOUNT('cfpb fact_complaints'[complaint_id])
		formatString: 0
		lineageTag: 6b916ab6-c629-41b5-9be8-d065ef9674ee

	measure 'Untimely Response Complaints' =
			
			CALCULATE(
			    DISTINCTCOUNT('cfpb fact_complaints'[complaint_id]),
			    FILTER(
			        'cfpb fact_complaints',
			        'cfpb fact_complaints'[timely_response] = FALSE()
			    )
			)
		formatString: 0
		lineageTag: eb7418f0-caf9-4ffd-b53c-75257d5e0d93

	measure 'Untimely Complaint Response Rate' =
			
			DIVIDE([Untimely Response Complaints], [Complaints], 0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 3e41d144-4850-4ea5-af85-3a560f179a63

	column complaint_id
		dataType: int64
		formatString: 0
		lineageTag: e31ccfc5-b6d4-4997-9d21-0360032bd3b8
		summarizeBy: sum
		sourceColumn: complaint_id

		annotation SummarizationSetBy = Automatic

	column complaint_fact_key
		dataType: int64
		formatString: 0
		lineageTag: 042f5808-ef89-4ce8-836a-aecdc7b10633
		summarizeBy: sum
		sourceColumn: complaint_fact_key

		annotation SummarizationSetBy = Automatic

	column date_received_key
		dataType: int64
		formatString: 0
		lineageTag: 85402e96-ccc4-4216-bb7a-359f862032b5
		summarizeBy: none
		sourceColumn: date_received_key

		annotation SummarizationSetBy = Automatic

	column date_sent_key
		dataType: int64
		formatString: 0
		lineageTag: 5491bafa-aa2b-4ed6-8e15-3b3f1fc4b83f
		summarizeBy: sum
		sourceColumn: date_sent_key

		annotation SummarizationSetBy = Automatic

	column product_key
		dataType: int64
		formatString: 0
		lineageTag: 5cc69f12-ecb1-4a02-b1b4-962c9e744bbc
		summarizeBy: none
		sourceColumn: product_key

		annotation SummarizationSetBy = Automatic

	column sub_product_key
		dataType: int64
		formatString: 0
		lineageTag: 48073692-7f75-43f7-8414-18a05039d529
		summarizeBy: none
		sourceColumn: sub_product_key

		annotation SummarizationSetBy = Automatic

	column issue_key
		dataType: int64
		formatString: 0
		lineageTag: 2e49d93d-6552-49cb-9794-d96e7d4576a3
		summarizeBy: none
		sourceColumn: issue_key

		annotation SummarizationSetBy = Automatic

	column sub_issue_key
		dataType: int64
		formatString: 0
		lineageTag: e1114c5a-5af9-44e0-8d3a-14b314aa99e5
		summarizeBy: none
		sourceColumn: sub_issue_key

		annotation SummarizationSetBy = Automatic

	column company_key
		dataType: int64
		formatString: 0
		lineageTag: 94679ca6-0d5d-4df2-874a-fa16a5780853
		summarizeBy: none
		sourceColumn: company_key

		annotation SummarizationSetBy = Automatic

	column state_key
		dataType: int64
		formatString: 0
		lineageTag: e4b13be2-d688-44ab-a376-36bc7b3f1342
		summarizeBy: none
		sourceColumn: state_key

		annotation SummarizationSetBy = Automatic

	column zip_code_key
		dataType: int64
		formatString: 0
		lineageTag: 68812a4b-1123-41b4-bd90-75c50dd33ed6
		summarizeBy: none
		sourceColumn: zip_code_key

		annotation SummarizationSetBy = Automatic

	column origin_key
		dataType: int64
		formatString: 0
		lineageTag: 94cc1d0c-4560-4b7b-b074-8c5c0854938c
		summarizeBy: none
		sourceColumn: origin_key

		annotation SummarizationSetBy = Automatic

	column public_response_key
		dataType: int64
		formatString: 0
		lineageTag: bd5e3a65-7ae4-452f-98a9-deb81c4ab4f5
		summarizeBy: none
		sourceColumn: public_response_key

		annotation SummarizationSetBy = Automatic

	column consent_key
		dataType: int64
		formatString: 0
		lineageTag: 741d83ce-1a93-4184-9e01-3cdeeee2a395
		summarizeBy: none
		sourceColumn: consent_key

		annotation SummarizationSetBy = Automatic

	column tag_key
		dataType: int64
		formatString: 0
		lineageTag: 70811247-7e1e-469f-8787-e9fae05eb4ac
		summarizeBy: none
		sourceColumn: tag_key

		annotation SummarizationSetBy = Automatic

	column disputed_key
		dataType: int64
		formatString: 0
		lineageTag: 11813252-896a-4c67-bf57-455d402d2616
		summarizeBy: none
		sourceColumn: disputed_key

		annotation SummarizationSetBy = Automatic

	column timely_response
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 3da6496e-9adf-4b12-bc35-893b0da74671
		summarizeBy: none
		sourceColumn: timely_response

		annotation SummarizationSetBy = Automatic

	column company_response_key
		dataType: int64
		formatString: 0
		lineageTag: 84f51635-4ef4-4e1c-84e1-ae0e05bcd8e6
		summarizeBy: none
		sourceColumn: company_response_key

		annotation SummarizationSetBy = Automatic

	partition 'cfpb fact_complaints' = m
		mode: import
		source =
				let
				    Source = MySQL.Database("localhost", "cfpb", [ReturnSingleDatabase=true, CreateNavigationProperties=false]),
				    cfpb_fact_complaints = Source{[Schema="cfpb",Item="fact_complaints"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(cfpb_fact_complaints,{"consumer_complaint_narrative"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Columns", each ([company_key] <> 1 and [company_key] <> 2 and [company_key] <> 3))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

