table 'cfpb dim_date'
	lineageTag: 6c6ee946-2455-4cd4-94a3-767d594baf33
	dataCategory: Time

	column full_date
		dataType: dateTime
		isKey
		formatString: Short Date
		lineageTag: f98e79e5-efd6-469d-b351-db1c7c26e297
		summarizeBy: none
		sourceColumn: full_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column year
		dataType: int64
		formatString: 0
		lineageTag: bac0a2aa-4652-4974-95b4-d9c8592b56c2
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: 68e9d6ec-9b63-427d-95a9-df601cb16a3a
		summarizeBy: none
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: a05e36f1-eae8-48ef-abaf-d942c1050678
		summarizeBy: none
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column day
		dataType: int64
		formatString: 0
		lineageTag: b171cda5-43b5-4478-93a0-9814a64ecc2d
		summarizeBy: none
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column date_key
		dataType: int64
		formatString: 0
		lineageTag: 64779a5a-7129-4b41-8d6e-2aaa7817684b
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column day_of_week_number
		dataType: int64
		formatString: 0
		lineageTag: ee4e9785-53e0-4f13-99e7-8fcd2feddce8
		summarizeBy: none
		sourceColumn: day_of_week_number

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 33302670-558b-45fd-910a-0236829bb0cc
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: month

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column day_name
		dataType: string
		lineageTag: 8605fe15-b792-447c-9d13-125d6afad524
		summarizeBy: none
		sourceColumn: day_name

		annotation SummarizationSetBy = Automatic

	column week_of_year
		dataType: int64
		formatString: 0
		lineageTag: d7e32dc6-113f-4087-98c2-6ddf71623847
		summarizeBy: none
		sourceColumn: week_of_year

		annotation SummarizationSetBy = Automatic

	column day_of_year
		dataType: int64
		formatString: 0
		lineageTag: 634976f6-8fef-4923-90dc-c8cd01a03769
		summarizeBy: none
		sourceColumn: day_of_year

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: cb0aadeb-5568-4b8c-ac30-5fbdd9d2f41b
		summarizeBy: none
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column is_month_end
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6791e02d-80c4-4080-b9ff-55dcb5956796
		summarizeBy: none
		sourceColumn: is_month_end

		annotation SummarizationSetBy = Automatic

	column is_quarter_end
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 71e1668a-a826-4bd8-bd9a-5f635456ed1e
		summarizeBy: none
		sourceColumn: is_quarter_end

		annotation SummarizationSetBy = Automatic

	column is_year_end
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c23fc0b9-2df9-4c41-9669-5d5228ecc617
		summarizeBy: none
		sourceColumn: is_year_end

		annotation SummarizationSetBy = Automatic

	column fiscal_year
		dataType: int64
		formatString: 0
		lineageTag: d5e7999d-da66-44f2-89bf-12458a3de64f
		summarizeBy: none
		sourceColumn: fiscal_year

		annotation SummarizationSetBy = Automatic

	column fiscal_quarter
		dataType: int64
		formatString: 0
		lineageTag: d509ab14-c48e-4a1e-be07-2c29b33053f1
		summarizeBy: none
		sourceColumn: fiscal_quarter

		annotation SummarizationSetBy = Automatic

	column fiscal_month
		dataType: int64
		formatString: 0
		lineageTag: 0e539cf3-1d9a-4f3a-8044-4a9d8b1df326
		summarizeBy: none
		sourceColumn: fiscal_month

		annotation SummarizationSetBy = Automatic

	partition 'cfpb dim_date' = m
		mode: import
		source =
				let
				    Source = MySQL.Database("localhost", "cfpb", [ReturnSingleDatabase=true, CreateNavigationProperties=false]),
				    cfpb_dim_date = Source{[Schema="cfpb",Item="dim_date"]}[Data],
				    #"Sorted Rows" = Table.Sort(cfpb_dim_date,{{"full_date", Order.Descending}}),
				    #"Filtered Rows" = Table.SelectRows(#"Sorted Rows", each true)
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

