table 'cfpb fact_complaints'
	lineageTag: a43a55d0-99b8-4057-b7cd-2d16fbeb8ead

	measure Total_Complaints_Today =
			
			CALCULATE(
			    COUNTROWS('cfpb fact_complaints'),
			    FILTER(
			        'cfpb dim_date',
			        'cfpb dim_date'[full_date] <= TODAY()
			    )
			)
		displayFolder: [complaints]
		lineageTag: ef7cdd6a-c7ae-4830-8b64-841599fed968

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Total_Complaints_30_Days_Ago =
			
			VAR SelectedDate = MAX('cfpb dim_date'[full_date])
			RETURN
			CALCULATE(
			    COUNTROWS('cfpb fact_complaints'),
			    FILTER(
			        'cfpb dim_date',
			        'cfpb dim_date'[full_date] <= SelectedDate - 30
			    )
			)
		formatString: 0
		displayFolder: [complaints]
		lineageTag: d4df4910-f3a0-434b-8446-387964b10eb3

	measure Total_Complaints_60_Days_Ago =
			
			VAR SelectedDate = MAX('cfpb dim_date'[full_date])
			RETURN
			CALCULATE(
			    COUNTROWS('cfpb fact_complaints'),
			    FILTER(
			        'cfpb dim_date',
			        'cfpb dim_date'[full_date] <= SelectedDate - 60
			    )
			)
		formatString: 0
		displayFolder: [complaints]
		lineageTag: 6c54f96e-41c9-446c-8ffe-edf22771ea25

	measure Complaints_Same_Period_Last_Year =
			
			VAR SelectedDate = MAX('cfpb dim_date'[full_date])
			VAR StartDateLY = SelectedDate - 395
			VAR EndDateLY = SelectedDate - 365
			RETURN
			CALCULATE(
			    COUNTROWS('cfpb fact_complaints'),
			    FILTER(
			        'cfpb dim_date',
			        'cfpb dim_date'[full_date] >= StartDateLY &&
			        'cfpb dim_date'[full_date] <= EndDateLY
			    )
			)
		formatString: 0
		displayFolder: [complaints]
		lineageTag: c73ab5f8-c694-4150-bf6a-b088a533cdff

	measure 'Complaints Vs 30 Days' = ```
			
			VAR t = [Total_Complaints_Today] // Complaints today
			VAR p = [Total_Complaints_30_Days_Ago] // Complaints previous 30 days
			VAR r = t - p // Complaint difference betweet today and prev 30 days
			VAR pc = DIVIDE(r, t, 0) // Percentage change
			VAR direction = IF(r >= 0, "↑", "↓")
			
			RETURN
			direction & " " & FORMAT(ABS(r), "#,0") & " vs 30 days (" & FORMAT(ABS(pc), "0.0%") & " change)"
			
			
			```
		displayFolder: [complaints][comparison]
		lineageTag: 3aecdccb-fe12-43f5-ad98-823d045c4ed7

	measure Complaints_Change_Color_Code = IF([Total_Complaints_Today] - [Total_Complaints_30_Days_Ago] >= 0, 1, 0)
		formatString: 0
		displayFolder: [complaints][color_coding]
		lineageTag: d758efd7-fb53-4d43-ac94-0535f93e188e

	measure 'Complaints Vs 60 Days' = ```
			
			VAR t = [Total_Complaints_Today] // Complaints today
			VAR p = [Total_Complaints_60_Days_Ago] // Complaints previous 60 days
			VAR r = t - p // Complaint difference betweet today and prev 60 days
			VAR pc = DIVIDE(r, t, 0) // Percentage change
			VAR direction = IF(r >= 0, "↑", "↓")
			
			RETURN
			direction & " " & FORMAT(ABS(r), "#,0") & " vs 60 days (" & FORMAT(ABS(pc), "0.0%") & " change)"
			
			
			```
		displayFolder: [complaints][comparison]
		lineageTag: d2dc4cf9-e709-4ac4-adaa-58eb0325f0b7

	measure 'Complaints Vs Same Period Last Year' = ```
			
			VAR t = [Total_Complaints_Today] // Complaints today
			VAR p = [Complaints_Same_Period_Last_Year] // Complaints previous year
			VAR r = t - p // Complaint difference betweet today and prev year
			VAR pc = DIVIDE(r, t, 0) // Percentage change
			VAR direction = IF(r >= 0, "↑", "↓")
			
			RETURN
			direction & " " & FORMAT(ABS(r), "#,0") & " vs Same Period Last Year (" & FORMAT(ABS(pc), "0.0%") & " change)"
			
			
			```
		displayFolder: [complaints][comparison]
		lineageTag: dbae2ff2-953e-433d-99e1-16ead1da1f09

	measure Complaints = DISTINCTCOUNT('cfpb fact_complaints'[complaint_id])
		formatString: 0
		lineageTag: 6b916ab6-c629-41b5-9be8-d065ef9674ee

	measure Timely_Response_Rate =
			
			VAR t = CALCULATE(
			    DISTINCTCOUNT('cfpb fact_complaints'[complaint_id]),
			    FILTER('cfpb fact_complaints', 'cfpb fact_complaints'[timely_response_flag] = TRUE())
			)
			VAR total = CALCULATE(
			    DISTINCTCOUNT('cfpb fact_complaints'[complaint_id])
			)
			RETURN
			DIVIDE(t, total, 0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 1938fa06-398a-47c4-ba5f-80cc8d6bce2d

	measure 'Timely Response Complaints' =
			CALCULATE(
			    [Complaints],
			    FILTER('cfpb fact_complaints', 'cfpb fact_complaints'[timely_response_flag] = TRUE())
			)
		formatString: 0
		lineageTag: 560954c1-5034-4a93-8a66-ddcf6a3d5f05

	measure 'Not Timely Response Complaints' =
			CALCULATE(
			    [Complaints],
			    FILTER('cfpb fact_complaints', 'cfpb fact_complaints'[timely_response_flag] = FALSE())
			)
		formatString: 0
		lineageTag: 412a8d3e-5018-44bd-98d8-028b2010c071

	column complaint_id
		dataType: int64
		formatString: 0
		lineageTag: e31ccfc5-b6d4-4997-9d21-0360032bd3b8
		summarizeBy: sum
		sourceColumn: complaint_id

		annotation SummarizationSetBy = Automatic

	column date_received_id
		dataType: int64
		formatString: 0
		lineageTag: 0d68ef4b-0f21-4ed5-83bc-8b4dd163aa8e
		summarizeBy: none
		sourceColumn: date_received_id

		annotation SummarizationSetBy = Automatic

	column date_sent_id
		dataType: int64
		formatString: 0
		lineageTag: 57f56c5a-7bc7-426c-a738-c1354915d3b6
		summarizeBy: sum
		sourceColumn: date_sent_id

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: int64
		formatString: 0
		lineageTag: e7dc4301-75a3-462f-b8e0-dd35148e32ab
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column sub_product_id
		dataType: int64
		formatString: 0
		lineageTag: 3d38481f-d5ab-48cf-af48-89aca747432f
		summarizeBy: none
		sourceColumn: sub_product_id

		annotation SummarizationSetBy = Automatic

	column issue_id
		dataType: int64
		formatString: 0
		lineageTag: 2dc07030-bba2-4525-aa16-de83a4de0958
		summarizeBy: none
		sourceColumn: issue_id

		annotation SummarizationSetBy = Automatic

	column sub_issue_id
		dataType: int64
		formatString: 0
		lineageTag: ea5fa9e3-290d-4350-8c90-4d785c2e6bd1
		summarizeBy: none
		sourceColumn: sub_issue_id

		annotation SummarizationSetBy = Automatic

	column company_id
		dataType: int64
		formatString: 0
		lineageTag: 8e00de59-b82a-4f31-964d-369157ae7e44
		summarizeBy: none
		sourceColumn: company_id

		annotation SummarizationSetBy = Automatic

	column state_id
		dataType: int64
		formatString: 0
		lineageTag: 74157021-52fd-4899-b452-0201ffe1a118
		summarizeBy: none
		sourceColumn: state_id

		annotation SummarizationSetBy = Automatic

	column zip_code_id
		dataType: int64
		formatString: 0
		lineageTag: 57625d62-99db-4858-8678-b89fae2a1548
		summarizeBy: none
		sourceColumn: zip_code_id

		annotation SummarizationSetBy = Automatic

	column origin_id
		dataType: int64
		formatString: 0
		lineageTag: 254df96d-a1c6-43af-8032-872786cfb61d
		summarizeBy: none
		sourceColumn: origin_id

		annotation SummarizationSetBy = Automatic

	column public_response_id
		dataType: int64
		formatString: 0
		lineageTag: bf96087c-163c-448c-93f6-3779d87124f8
		summarizeBy: none
		sourceColumn: public_response_id

		annotation SummarizationSetBy = Automatic

	column status_id
		dataType: int64
		formatString: 0
		lineageTag: a3a802c8-2ba0-4c0f-a383-c1ee18f23999
		summarizeBy: none
		sourceColumn: status_id

		annotation SummarizationSetBy = Automatic

	column consent_id
		dataType: int64
		formatString: 0
		lineageTag: b7be0777-a44a-4e9e-b97e-7f8620376a3d
		summarizeBy: none
		sourceColumn: consent_id

		annotation SummarizationSetBy = Automatic

	column tag_id
		dataType: int64
		formatString: 0
		lineageTag: 5c58e90d-daaa-4555-8bd2-7e24bac898ac
		summarizeBy: none
		sourceColumn: tag_id

		annotation SummarizationSetBy = Automatic

	column disputed_id
		dataType: int64
		formatString: 0
		lineageTag: 9fbeb9a5-ed97-4fb8-8ec7-7d400f2861fc
		summarizeBy: none
		sourceColumn: disputed_id

		annotation SummarizationSetBy = Automatic

	column consumer_narrative
		dataType: string
		lineageTag: 8a804b15-c9da-4e23-aa8f-a74241327ba4
		summarizeBy: none
		sourceColumn: consumer_narrative

		annotation SummarizationSetBy = Automatic

	column timely_response_flag
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: cd81dd38-3bd9-482f-8ea2-0f929d54acc3
		summarizeBy: none
		sourceColumn: timely_response_flag

		annotation SummarizationSetBy = Automatic

	partition 'cfpb fact_complaints' = m
		mode: import
		source =
				let
				    Source = MySQL.Database("localhost", "cfpb", [ReturnSingleDatabase=true]),
				    cfpb_fact_complaints = Source{[Schema="cfpb",Item="fact_complaints"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(cfpb_fact_complaints, each ([company_id] <> 1 and [company_id] <> 2 and [company_id] <> 3))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

