table 'cfpb dim_company_response'
	lineageTag: f5bbc4a7-5c51-4048-ac73-734cd26d9688

	measure 'Monetary Relief Complaints' = CALCULATE(DISTINCTCOUNT('cfpb fact_complaints'[complaint_id]), FILTER('cfpb dim_company_response', 'cfpb dim_company_response'[response_description] = "Monetary Relief"))
		formatString: 0
		lineageTag: 9710cfc2-9098-4639-9283-5b42136a2767

	column response_key
		dataType: int64
		formatString: 0
		lineageTag: be2f89b0-9f6f-44ad-a2ee-a43df3202193
		summarizeBy: none
		sourceColumn: response_key

		annotation SummarizationSetBy = Automatic

	column response_description
		dataType: string
		lineageTag: 8db8c364-2e17-4cbf-af14-c01294f571dd
		summarizeBy: none
		sourceColumn: response_description

		annotation SummarizationSetBy = Automatic

	partition 'cfpb dim_company_response' = m
		mode: import
		source =
				let
				    Source = MySQL.Database("localhost", "cfpb", [ReturnSingleDatabase=true, CreateNavigationProperties=false]),
				    cfpb_dim_company_response = Source{[Schema="cfpb",Item="dim_company_response"]}[Data]
				in
				    cfpb_dim_company_response

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

