table 'cfpb dim_disputed'
	lineageTag: 2dd1fc45-bed1-4c5d-8f2e-2aa40227ebc4

	measure 'Disputed Complaints Rate' = ```
			
			VAR c = [Complaints]
			VAR cd = CALCULATE([Complaints], FILTER('cfpb dim_disputed', 'cfpb dim_disputed'[disputed_status] = "Yes"))
			VAR cdr = DIVIDE(cd, c, 0)
			RETURN 
			    IF(ISBLANK(cdr), "N/A", cdr)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 395e05ff-03db-4895-ae4c-ff49ba3f4d06

	measure 'Not Disputed Complaints Rate' = ```
			
			VAR c = [Complaints]
			VAR cd = CALCULATE([Complaints], FILTER('cfpb dim_disputed', 'cfpb dim_disputed'[disputed_status] = "No"))
			VAR cdr = DIVIDE(cd, c, 0)
			RETURN 
			    IF(ISBLANK(cdr), "N/A", cdr)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: ecdfdce2-4381-4c43-9257-5a11285148ad

	measure 'Disputed Not Available Complaints Rate' = ```
			
			VAR c = [Complaints]
			VAR cd = CALCULATE([Complaints], FILTER('cfpb dim_disputed', 'cfpb dim_disputed'[disputed_status] = "N/A"))
			VAR cdr = DIVIDE(cd, c, 0)
			RETURN 
			    IF(ISBLANK(cdr), "N/A", cdr)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c8c00c65-88a3-45a1-a897-839f570bfb8b

	column disputed_key
		dataType: int64
		formatString: 0
		lineageTag: 3572a0c9-8113-4125-8d25-1193b00ec867
		summarizeBy: none
		sourceColumn: disputed_key

		annotation SummarizationSetBy = Automatic

	column disputed_status
		dataType: string
		lineageTag: 2f7fb293-2609-45b4-986e-e04c7557b00a
		summarizeBy: none
		sourceColumn: disputed_status

		annotation SummarizationSetBy = Automatic

	partition 'cfpb dim_disputed' = m
		mode: import
		source =
				let
				    Source = MySQL.Database("localhost", "cfpb", [ReturnSingleDatabase=true, CreateNavigationProperties=false]),
				    cfpb_dim_disputed = Source{[Schema="cfpb",Item="dim_disputed"]}[Data]
				in
				    cfpb_dim_disputed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

