table 'cfpb dim_company'
	lineageTag: 5b36a673-3633-4c82-86a8-dc2e0c72f491

	column company_key
		dataType: int64
		formatString: 0
		lineageTag: d1afee2c-6cd0-4fa9-b1df-2d505ddc63c0
		summarizeBy: none
		sourceColumn: company_key

		annotation SummarizationSetBy = Automatic

	column company_name
		dataType: string
		lineageTag: 26b0d3d6-28e1-42b4-959f-d867f41a5be7
		summarizeBy: none
		sourceColumn: company_name

		annotation SummarizationSetBy = Automatic

	partition 'cfpb dim_company' = m
		mode: import
		source =
				let
				    Source = MySQL.Database("localhost", "cfpb", [ReturnSingleDatabase=true, CreateNavigationProperties=false]),
				    cfpb_dim_company = Source{[Schema="cfpb",Item="dim_company"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(cfpb_dim_company, each true),
				    #"Capitalized Each Word" = Table.TransformColumns(#"Filtered Rows",{{"company_name", Text.Proper, type text}})
				in
				    #"Capitalized Each Word"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

