table 'cfpb dim_date'
	lineageTag: 6c6ee946-2455-4cd4-94a3-767d594baf33
	dataCategory: Time

	column full_date
		dataType: dateTime
		isKey
		formatString: Short Date
		lineageTag: f98e79e5-efd6-469d-b351-db1c7c26e297
		summarizeBy: none
		sourceColumn: full_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column year
		dataType: int64
		formatString: 0
		lineageTag: bac0a2aa-4652-4974-95b4-d9c8592b56c2
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: 68e9d6ec-9b63-427d-95a9-df601cb16a3a
		summarizeBy: none
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		formatString: 0
		lineageTag: a05e36f1-eae8-48ef-abaf-d942c1050678
		summarizeBy: none
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column day
		dataType: int64
		formatString: 0
		lineageTag: b171cda5-43b5-4478-93a0-9814a64ecc2d
		summarizeBy: none
		sourceColumn: day

		annotation SummarizationSetBy = Automatic

	column date_key
		dataType: int64
		formatString: 0
		lineageTag: 64779a5a-7129-4b41-8d6e-2aaa7817684b
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column day_of_week_number
		dataType: int64
		formatString: 0
		lineageTag: ee4e9785-53e0-4f13-99e7-8fcd2feddce8
		summarizeBy: none
		sourceColumn: day_of_week_number

		annotation SummarizationSetBy = Automatic

	partition 'cfpb dim_date' = m
		mode: import
		source =
				let
				    Source = MySQL.Database("localhost", "cfpb", [ReturnSingleDatabase=true]),
				    cfpb_dim_date = Source{[Schema="cfpb",Item="dim_date"]}[Data],
				    #"Sorted Rows" = Table.Sort(cfpb_dim_date,{{"full_date", Order.Descending}}),
				    #"Filtered Rows" = Table.SelectRows(#"Sorted Rows", each true)
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

