table 'cfpb dim_disputed'
	lineageTag: 2dd1fc45-bed1-4c5d-8f2e-2aa40227ebc4

	measure 'Disputed Complaints Rate' = ```
			
			VAR c = [Complaints]
			VAR cd = CALCULATE([Complaints], FILTER('cfpb dim_disputed', 'cfpb dim_disputed'[disputed] = "Yes"))
			VAR cdr = DIVIDE(cd, c, 0)
			RETURN 
			    IF(ISBLANK(cdr), "N/A", cdr)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 395e05ff-03db-4895-ae4c-ff49ba3f4d06

	measure 'Not Disputed Complaints Rate' = ```
			
			VAR c = [Complaints]
			VAR cd = CALCULATE([Complaints], FILTER('cfpb dim_disputed', 'cfpb dim_disputed'[disputed] = "No"))
			VAR cdr = DIVIDE(cd, c, 0)
			RETURN 
			    IF(ISBLANK(cdr), "N/A", cdr)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: ecdfdce2-4381-4c43-9257-5a11285148ad

	measure 'Disputed Not Available Complaints Rate' = ```
			
			VAR c = [Complaints]
			VAR cd = CALCULATE([Complaints], FILTER('cfpb dim_disputed', 'cfpb dim_disputed'[disputed] = "N/A"))
			VAR cdr = DIVIDE(cd, c, 0)
			RETURN 
			    IF(ISBLANK(cdr), "N/A", cdr)
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c8c00c65-88a3-45a1-a897-839f570bfb8b

	column disputed_id
		dataType: int64
		formatString: 0
		lineageTag: 2e402205-ee24-4797-8761-1fd3923e7b6f
		summarizeBy: none
		sourceColumn: disputed_id

		annotation SummarizationSetBy = Automatic

	column disputed
		dataType: string
		lineageTag: 3677fd10-3671-4a2c-852f-5a6048470c0c
		summarizeBy: none
		sourceColumn: disputed

		annotation SummarizationSetBy = Automatic

	partition 'cfpb dim_disputed' = m
		mode: import
		source =
				let
				    Source = MySQL.Database("localhost", "cfpb", [ReturnSingleDatabase=true]),
				    cfpb_dim_disputed = Source{[Schema="cfpb",Item="dim_disputed"]}[Data]
				in
				    cfpb_dim_disputed

